
%---------------------------------------------------------------------------------------------------
% FACT: rpz_process(ProcessID, ParentID, RunID, IsThread, ExitCode, TimeStamp).
%---------------------------------------------------------------------------------------------------
rpz_process(p1, nil, r0, false, 0, nil).
rpz_process(p2, p1, r0, false, 0, nil).

%---------------------------------------------------------------------------------------------------
% FACT: rpz_execution(ExecID, RunID, ProcessID, FilePath, WorkingDir, TimeStamp).
%---------------------------------------------------------------------------------------------------
rpz_execution(e1, r0, p1, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./run.sh', '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python', nil).
rpz_execution(e2, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./hello.py', '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python', nil).
rpz_execution(e3, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python', '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python', nil).

%---------------------------------------------------------------------------------------------------
% FACT: rpz_argument(ExecID, ArgIndex, ArgValue).
%---------------------------------------------------------------------------------------------------
rpz_argument(e1, 0, './run.sh').
rpz_argument(e2, 0, './hello.py').
rpz_argument(e3, 0, 'python').
rpz_argument(e3, 1, './hello.py').

%---------------------------------------------------------------------------------------------------
% FACT: rpz_opened(FileID, RunID, ProcessID, FilePath, Mode, IsDirectory, Timestamp).
%---------------------------------------------------------------------------------------------------
rpz_opened(o18, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python', 4, true, nil).
rpz_opened(o19, r0, p2, '/usr/bin/env', 1, false, nil).
rpz_opened(o20, r0, p2, '/usr/bin/env', 1, false, nil).
rpz_opened(o21, r0, p2, '/lib/x86_64-linux-gnu/ld-2.24.so', 1, false, nil).
rpz_opened(o22, r0, p2, '/etc/ld.so.cache', 1, false, nil).
rpz_opened(o23, r0, p2, '/lib/x86_64-linux-gnu/libc.so.6', 1, false, nil).
rpz_opened(o24, r0, p2, '/usr/lib/locale/locale-archive', 1, false, nil).
rpz_opened(o25, r0, p2, '/usr/bin/python3.5', 1, false, nil).
rpz_opened(o26, r0, p2, '/lib/x86_64-linux-gnu/ld-2.24.so', 1, false, nil).
rpz_opened(o27, r0, p2, '/etc/ld.so.cache', 1, false, nil).
rpz_opened(o28, r0, p2, '/lib/x86_64-linux-gnu/libpthread.so.0', 1, false, nil).
rpz_opened(o29, r0, p2, '/lib/x86_64-linux-gnu/libdl.so.2', 1, false, nil).
rpz_opened(o30, r0, p2, '/lib/x86_64-linux-gnu/libutil.so.1', 1, false, nil).
rpz_opened(o31, r0, p2, '/lib/x86_64-linux-gnu/libexpat.so.1', 1, false, nil).
rpz_opened(o32, r0, p2, '/lib/x86_64-linux-gnu/libz.so.1', 1, false, nil).
rpz_opened(o33, r0, p2, '/lib/x86_64-linux-gnu/libm.so.6', 1, false, nil).
rpz_opened(o34, r0, p2, '/lib/x86_64-linux-gnu/libc.so.6', 1, false, nil).
rpz_opened(o35, r0, p2, '/usr/lib/locale/locale-archive', 1, false, nil).
rpz_opened(o36, r0, p2, '/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache', 1, false, nil).
rpz_opened(o37, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python', 8, false, nil).
rpz_opened(o38, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python', 24, false, nil).
rpz_opened(o39, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python3', 24, false, nil).
rpz_opened(o40, r0, p2, '/usr/bin/python3', 24, false, nil).
rpz_opened(o41, r0, p2, '/usr/lib/python3.5/os.py', 8, false, nil).
rpz_opened(o42, r0, p2, '/usr/lib/python3.5/lib-dynload', 8, true, nil).
rpz_opened(o43, r0, p2, '/usr/lib', 8, true, nil).
rpz_opened(o44, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o45, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o46, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o47, r0, p2, '/usr/lib/python3.5', 1, true, nil).
rpz_opened(o48, r0, p2, '/usr/lib/python3.5/encodings/__init__.py', 8, false, nil).
rpz_opened(o49, r0, p2, '/usr/lib/python3.5/encodings/__init__.py', 8, false, nil).
rpz_opened(o50, r0, p2, '/usr/lib/python3.5/encodings/__pycache__/__init__.cpython-35.pyc', 1, false, nil).
rpz_opened(o51, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o52, r0, p2, '/usr/lib/python3.5/codecs.py', 8, false, nil).
rpz_opened(o53, r0, p2, '/usr/lib/python3.5/codecs.py', 8, false, nil).
rpz_opened(o54, r0, p2, '/usr/lib/python3.5/__pycache__/codecs.cpython-35.pyc', 1, false, nil).
rpz_opened(o55, r0, p2, '/usr/lib/python3.5/encodings', 8, true, nil).
rpz_opened(o56, r0, p2, '/usr/lib/python3.5/encodings', 8, true, nil).
rpz_opened(o57, r0, p2, '/usr/lib/python3.5/encodings', 8, true, nil).
rpz_opened(o58, r0, p2, '/usr/lib/python3.5/encodings', 1, true, nil).
rpz_opened(o59, r0, p2, '/usr/lib/python3.5/encodings/aliases.py', 8, false, nil).
rpz_opened(o60, r0, p2, '/usr/lib/python3.5/encodings/aliases.py', 8, false, nil).
rpz_opened(o61, r0, p2, '/usr/lib/python3.5/encodings/__pycache__/aliases.cpython-35.pyc', 1, false, nil).
rpz_opened(o62, r0, p2, '/usr/lib/python3.5/encodings', 8, true, nil).
rpz_opened(o63, r0, p2, '/usr/lib/python3.5/encodings/utf_8.py', 8, false, nil).
rpz_opened(o64, r0, p2, '/usr/lib/python3.5/encodings/utf_8.py', 8, false, nil).
rpz_opened(o65, r0, p2, '/usr/lib/python3.5/encodings/__pycache__/utf_8.cpython-35.pyc', 1, false, nil).
rpz_opened(o66, r0, p2, '/usr/lib/python3.5/encodings', 8, true, nil).
rpz_opened(o67, r0, p2, '/usr/lib/python3.5/encodings/latin_1.py', 8, false, nil).
rpz_opened(o68, r0, p2, '/usr/lib/python3.5/encodings/latin_1.py', 8, false, nil).
rpz_opened(o69, r0, p2, '/usr/lib/python3.5/encodings/__pycache__/latin_1.cpython-35.pyc', 1, false, nil).
rpz_opened(o70, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o71, r0, p2, '/usr/lib/python3.5/io.py', 8, false, nil).
rpz_opened(o72, r0, p2, '/usr/lib/python3.5/io.py', 8, false, nil).
rpz_opened(o73, r0, p2, '/usr/lib/python3.5/__pycache__/io.cpython-35.pyc', 1, false, nil).
rpz_opened(o74, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o75, r0, p2, '/usr/lib/python3.5/abc.py', 8, false, nil).
rpz_opened(o76, r0, p2, '/usr/lib/python3.5/abc.py', 8, false, nil).
rpz_opened(o77, r0, p2, '/usr/lib/python3.5/__pycache__/abc.cpython-35.pyc', 1, false, nil).
rpz_opened(o78, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o79, r0, p2, '/usr/lib/python3.5/_weakrefset.py', 8, false, nil).
rpz_opened(o80, r0, p2, '/usr/lib/python3.5/_weakrefset.py', 8, false, nil).
rpz_opened(o81, r0, p2, '/usr/lib/python3.5/__pycache__/_weakrefset.cpython-35.pyc', 1, false, nil).
rpz_opened(o82, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o83, r0, p2, '/usr/lib/python3.5/site.py', 8, false, nil).
rpz_opened(o84, r0, p2, '/usr/lib/python3.5/site.py', 8, false, nil).
rpz_opened(o85, r0, p2, '/usr/lib/python3.5/__pycache__/site.cpython-35.pyc', 1, false, nil).
rpz_opened(o86, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o87, r0, p2, '/usr/lib/python3.5/os.py', 8, false, nil).
rpz_opened(o88, r0, p2, '/usr/lib/python3.5/os.py', 8, false, nil).
rpz_opened(o89, r0, p2, '/usr/lib/python3.5/__pycache__/os.cpython-35.pyc', 1, false, nil).
rpz_opened(o90, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o91, r0, p2, '/usr/lib/python3.5/stat.py', 8, false, nil).
rpz_opened(o92, r0, p2, '/usr/lib/python3.5/stat.py', 8, false, nil).
rpz_opened(o93, r0, p2, '/usr/lib/python3.5/__pycache__/stat.cpython-35.pyc', 1, false, nil).
rpz_opened(o94, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o95, r0, p2, '/usr/lib/python3.5/posixpath.py', 8, false, nil).
rpz_opened(o96, r0, p2, '/usr/lib/python3.5/posixpath.py', 8, false, nil).
rpz_opened(o97, r0, p2, '/usr/lib/python3.5/__pycache__/posixpath.cpython-35.pyc', 1, false, nil).
rpz_opened(o98, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o99, r0, p2, '/usr/lib/python3.5/genericpath.py', 8, false, nil).
rpz_opened(o100, r0, p2, '/usr/lib/python3.5/genericpath.py', 8, false, nil).
rpz_opened(o101, r0, p2, '/usr/lib/python3.5/__pycache__/genericpath.cpython-35.pyc', 1, false, nil).
rpz_opened(o102, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o103, r0, p2, '/usr/lib/python3.5/_collections_abc.py', 8, false, nil).
rpz_opened(o104, r0, p2, '/usr/lib/python3.5/_collections_abc.py', 8, false, nil).
rpz_opened(o105, r0, p2, '/usr/lib/python3.5/__pycache__/_collections_abc.cpython-35.pyc', 1, false, nil).
rpz_opened(o106, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o107, r0, p2, '/usr/lib/python3.5/_sitebuiltins.py', 8, false, nil).
rpz_opened(o108, r0, p2, '/usr/lib/python3.5/_sitebuiltins.py', 8, false, nil).
rpz_opened(o109, r0, p2, '/usr/lib/python3.5/__pycache__/_sitebuiltins.cpython-35.pyc', 1, false, nil).
rpz_opened(o110, r0, p2, '/home/tmcphill/.venv/reprozip/pyvenv.cfg', 8, false, nil).
rpz_opened(o111, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o112, r0, p2, '/usr/lib/python3.5/re.py', 8, false, nil).
rpz_opened(o113, r0, p2, '/usr/lib/python3.5/re.py', 8, false, nil).
rpz_opened(o114, r0, p2, '/usr/lib/python3.5/__pycache__/re.cpython-35.pyc', 1, false, nil).
rpz_opened(o115, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o116, r0, p2, '/usr/lib/python3.5/sre_compile.py', 8, false, nil).
rpz_opened(o117, r0, p2, '/usr/lib/python3.5/sre_compile.py', 8, false, nil).
rpz_opened(o118, r0, p2, '/usr/lib/python3.5/__pycache__/sre_compile.cpython-35.pyc', 1, false, nil).
rpz_opened(o119, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o120, r0, p2, '/usr/lib/python3.5/sre_parse.py', 8, false, nil).
rpz_opened(o121, r0, p2, '/usr/lib/python3.5/sre_parse.py', 8, false, nil).
rpz_opened(o122, r0, p2, '/usr/lib/python3.5/__pycache__/sre_parse.cpython-35.pyc', 1, false, nil).
rpz_opened(o123, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o124, r0, p2, '/usr/lib/python3.5/sre_constants.py', 8, false, nil).
rpz_opened(o125, r0, p2, '/usr/lib/python3.5/sre_constants.py', 8, false, nil).
rpz_opened(o126, r0, p2, '/usr/lib/python3.5/__pycache__/sre_constants.cpython-35.pyc', 1, false, nil).
rpz_opened(o127, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o128, r0, p2, '/usr/lib/python3.5/copyreg.py', 8, false, nil).
rpz_opened(o129, r0, p2, '/usr/lib/python3.5/copyreg.py', 8, false, nil).
rpz_opened(o130, r0, p2, '/usr/lib/python3.5/__pycache__/copyreg.cpython-35.pyc', 1, false, nil).
rpz_opened(o131, r0, p2, '/home/tmcphill/.venv/reprozip/pyvenv.cfg', 1, false, nil).
rpz_opened(o132, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o133, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 1, true, nil).
rpz_opened(o134, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip-1.0.16-py3.6-nspkg.pth', 1, false, nil).
rpz_opened(o135, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o136, r0, p2, '/usr/lib/python3.5/_bootlocale.py', 8, false, nil).
rpz_opened(o137, r0, p2, '/usr/lib/python3.5/_bootlocale.py', 8, false, nil).
rpz_opened(o138, r0, p2, '/usr/lib/python3.5/__pycache__/_bootlocale.cpython-35.pyc', 1, false, nil).
rpz_opened(o139, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o140, r0, p2, '/usr/lib/python3.5/types.py', 8, false, nil).
rpz_opened(o141, r0, p2, '/usr/lib/python3.5/types.py', 8, false, nil).
rpz_opened(o142, r0, p2, '/usr/lib/python3.5/__pycache__/types.cpython-35.pyc', 1, false, nil).
rpz_opened(o143, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o144, r0, p2, '/usr/lib/python3.5/functools.py', 8, false, nil).
rpz_opened(o145, r0, p2, '/usr/lib/python3.5/functools.py', 8, false, nil).
rpz_opened(o146, r0, p2, '/usr/lib/python3.5/__pycache__/functools.cpython-35.pyc', 1, false, nil).
rpz_opened(o147, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o148, r0, p2, '/usr/lib/python3.5/collections/__init__.py', 8, false, nil).
rpz_opened(o149, r0, p2, '/usr/lib/python3.5/collections/__init__.py', 8, false, nil).
rpz_opened(o150, r0, p2, '/usr/lib/python3.5/collections/__pycache__/__init__.cpython-35.pyc', 1, false, nil).
rpz_opened(o151, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o152, r0, p2, '/usr/lib/python3.5/operator.py', 8, false, nil).
rpz_opened(o153, r0, p2, '/usr/lib/python3.5/operator.py', 8, false, nil).
rpz_opened(o154, r0, p2, '/usr/lib/python3.5/__pycache__/operator.cpython-35.pyc', 1, false, nil).
rpz_opened(o155, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o156, r0, p2, '/usr/lib/python3.5/keyword.py', 8, false, nil).
rpz_opened(o157, r0, p2, '/usr/lib/python3.5/keyword.py', 8, false, nil).
rpz_opened(o158, r0, p2, '/usr/lib/python3.5/__pycache__/keyword.cpython-35.pyc', 1, false, nil).
rpz_opened(o159, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o160, r0, p2, '/usr/lib/python3.5/heapq.py', 8, false, nil).
rpz_opened(o161, r0, p2, '/usr/lib/python3.5/heapq.py', 8, false, nil).
rpz_opened(o162, r0, p2, '/usr/lib/python3.5/__pycache__/heapq.cpython-35.pyc', 1, false, nil).
rpz_opened(o163, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o164, r0, p2, '/usr/lib/python3.5/reprlib.py', 8, false, nil).
rpz_opened(o165, r0, p2, '/usr/lib/python3.5/reprlib.py', 8, false, nil).
rpz_opened(o166, r0, p2, '/usr/lib/python3.5/__pycache__/reprlib.cpython-35.pyc', 1, false, nil).
rpz_opened(o167, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o168, r0, p2, '/usr/lib/python3.5/weakref.py', 8, false, nil).
rpz_opened(o169, r0, p2, '/usr/lib/python3.5/weakref.py', 8, false, nil).
rpz_opened(o170, r0, p2, '/usr/lib/python3.5/__pycache__/weakref.cpython-35.pyc', 1, false, nil).
rpz_opened(o171, r0, p2, '/usr/lib/python3.5/collections', 8, true, nil).
rpz_opened(o172, r0, p2, '/usr/lib/python3.5/collections', 8, true, nil).
rpz_opened(o173, r0, p2, '/usr/lib/python3.5/collections', 8, true, nil).
rpz_opened(o174, r0, p2, '/usr/lib/python3.5/collections', 1, true, nil).
rpz_opened(o175, r0, p2, '/usr/lib/python3.5/collections/abc.py', 8, false, nil).
rpz_opened(o176, r0, p2, '/usr/lib/python3.5/collections/abc.py', 8, false, nil).
rpz_opened(o177, r0, p2, '/usr/lib/python3.5/collections/__pycache__/abc.cpython-35.pyc', 1, false, nil).
rpz_opened(o178, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o179, r0, p2, '/usr/lib/python3.5/importlib/__init__.py', 8, false, nil).
rpz_opened(o180, r0, p2, '/usr/lib/python3.5/importlib/__init__.py', 8, false, nil).
rpz_opened(o181, r0, p2, '/usr/lib/python3.5/importlib/__pycache__/__init__.cpython-35.pyc', 1, false, nil).
rpz_opened(o182, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o183, r0, p2, '/usr/lib/python3.5/warnings.py', 8, false, nil).
rpz_opened(o184, r0, p2, '/usr/lib/python3.5/warnings.py', 8, false, nil).
rpz_opened(o185, r0, p2, '/usr/lib/python3.5/__pycache__/warnings.cpython-35.pyc', 1, false, nil).
rpz_opened(o186, r0, p2, '/usr/lib/python3.5/importlib', 8, true, nil).
rpz_opened(o187, r0, p2, '/usr/lib/python3.5/importlib', 8, true, nil).
rpz_opened(o188, r0, p2, '/usr/lib/python3.5/importlib', 8, true, nil).
rpz_opened(o189, r0, p2, '/usr/lib/python3.5/importlib', 1, true, nil).
rpz_opened(o190, r0, p2, '/usr/lib/python3.5/importlib/util.py', 8, false, nil).
rpz_opened(o191, r0, p2, '/usr/lib/python3.5/importlib/util.py', 8, false, nil).
rpz_opened(o192, r0, p2, '/usr/lib/python3.5/importlib/__pycache__/util.cpython-35.pyc', 1, false, nil).
rpz_opened(o193, r0, p2, '/usr/lib/python3.5/importlib', 8, true, nil).
rpz_opened(o194, r0, p2, '/usr/lib/python3.5/importlib/abc.py', 8, false, nil).
rpz_opened(o195, r0, p2, '/usr/lib/python3.5/importlib/abc.py', 8, false, nil).
rpz_opened(o196, r0, p2, '/usr/lib/python3.5/importlib/__pycache__/abc.cpython-35.pyc', 1, false, nil).
rpz_opened(o197, r0, p2, '/usr/lib/python3.5/importlib', 8, true, nil).
rpz_opened(o198, r0, p2, '/usr/lib/python3.5/importlib/machinery.py', 8, false, nil).
rpz_opened(o199, r0, p2, '/usr/lib/python3.5/importlib/machinery.py', 8, false, nil).
rpz_opened(o200, r0, p2, '/usr/lib/python3.5/importlib/__pycache__/machinery.cpython-35.pyc', 1, false, nil).
rpz_opened(o201, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o202, r0, p2, '/usr/lib/python3.5/contextlib.py', 8, false, nil).
rpz_opened(o203, r0, p2, '/usr/lib/python3.5/contextlib.py', 8, false, nil).
rpz_opened(o204, r0, p2, '/usr/lib/python3.5/__pycache__/contextlib.cpython-35.pyc', 1, false, nil).
rpz_opened(o205, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o206, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o207, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o208, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 1, true, nil).
rpz_opened(o209, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o210, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o211, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o212, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o213, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o214, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o215, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 1, true, nil).
rpz_opened(o216, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip/unpackers', 8, true, nil).
rpz_opened(o217, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o218, r0, p2, '/usr/lib/python3.5/sysconfig.py', 8, false, nil).
rpz_opened(o219, r0, p2, '/usr/lib/python3.5/sysconfig.py', 8, false, nil).
rpz_opened(o220, r0, p2, '/usr/lib/python3.5/__pycache__/sysconfig.cpython-35.pyc', 1, false, nil).
rpz_opened(o221, r0, p2, '/home', 24, true, nil).
rpz_opened(o222, r0, p2, '/home/tmcphill', 24, true, nil).
rpz_opened(o223, r0, p2, '/home/tmcphill/.venv', 24, true, nil).
rpz_opened(o224, r0, p2, '/home/tmcphill/.venv/reprozip', 24, true, nil).
rpz_opened(o225, r0, p2, '/home/tmcphill/.venv/reprozip/bin', 24, true, nil).
rpz_opened(o226, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python', 24, false, nil).
rpz_opened(o227, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python', 24, false, nil).
rpz_opened(o228, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python3', 24, false, nil).
rpz_opened(o229, r0, p2, '/home/tmcphill/.venv/reprozip/bin/python3', 24, false, nil).
rpz_opened(o230, r0, p2, '/usr', 24, true, nil).
rpz_opened(o231, r0, p2, '/usr/bin', 24, true, nil).
rpz_opened(o232, r0, p2, '/usr/bin/python3', 24, false, nil).
rpz_opened(o233, r0, p2, '/usr/bin/python3', 24, false, nil).
rpz_opened(o234, r0, p2, '/usr/bin/python3.5', 24, false, nil).
rpz_opened(o235, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o236, r0, p2, '/usr/lib/python3.5/_sysconfigdata.py', 8, false, nil).
rpz_opened(o237, r0, p2, '/usr/lib/python3.5/_sysconfigdata.py', 8, false, nil).
rpz_opened(o238, r0, p2, '/usr/lib/python3.5/__pycache__/_sysconfigdata.cpython-35.pyc', 1, false, nil).
rpz_opened(o239, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o240, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu', 8, true, nil).
rpz_opened(o241, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu', 8, true, nil).
rpz_opened(o242, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu', 8, true, nil).
rpz_opened(o243, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu', 1, true, nil).
rpz_opened(o244, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu/_sysconfigdata_m.py', 8, false, nil).
rpz_opened(o245, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu/_sysconfigdata_m.py', 8, false, nil).
rpz_opened(o246, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu/__pycache__/_sysconfigdata_m.cpython-35.pyc', 1, false, nil).
rpz_opened(o247, r0, p2, '/usr', 24, true, nil).
rpz_opened(o248, r0, p2, '/usr/lib', 24, true, nil).
rpz_opened(o249, r0, p2, '/usr/lib/python3.5', 24, true, nil).
rpz_opened(o250, r0, p2, '/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu', 24, true, nil).
rpz_opened(o251, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o252, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 1, true, nil).
rpz_opened(o253, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip-1.0.16-py3.6-nspkg.pth', 1, false, nil).
rpz_opened(o254, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o255, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o256, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o257, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o258, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip', 8, true, nil).
rpz_opened(o259, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages/reprounzip/unpackers', 8, true, nil).
rpz_opened(o260, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o261, r0, p2, '/usr/lib/python3.5/sitecustomize.py', 8, false, nil).
rpz_opened(o262, r0, p2, '/usr/lib/python3.5/sitecustomize.py', 8, false, nil).
rpz_opened(o263, r0, p2, '/usr/lib/python3.5/__pycache__/sitecustomize.cpython-35.pyc', 1, false, nil).
rpz_opened(o264, r0, p2, '/usr/lib/python3.5', 8, true, nil).
rpz_opened(o265, r0, p2, '/usr/lib/python3.5/plat-x86_64-linux-gnu', 8, true, nil).
rpz_opened(o266, r0, p2, '/usr/lib/python3.5/lib-dynload', 8, true, nil).
rpz_opened(o267, r0, p2, '/usr/lib/python3.5/lib-dynload', 8, true, nil).
rpz_opened(o268, r0, p2, '/usr/lib/python3.5/lib-dynload', 8, true, nil).
rpz_opened(o269, r0, p2, '/usr/lib/python3.5/lib-dynload', 1, true, nil).
rpz_opened(o270, r0, p2, '/home/tmcphill/.venv/reprozip/lib/python3.5/site-packages', 8, true, nil).
rpz_opened(o271, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/hello.py', 24, false, nil).
rpz_opened(o272, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./hello.py', 8, false, nil).
rpz_opened(o273, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./hello.py', 1, false, nil).
rpz_opened(o274, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./hello.py', 8, false, nil).
rpz_opened(o275, r0, p2, '/mnt/c/Users/tmcphill/OneDrive/GitRepos/wt-prov-model/examples/06-hello-python/./hello.py', 1, false, nil).
